name: ItemFrameCSV
author: "Kici33"
version: "1.0"
main: me.kici33.ItemFrame.IFrame

commands:
  loadsigns:
    permission: KItemFrame.loadsigns
    description: "Command is loading signs to shop from ItemFrames using spreadsheet"
